language: go

go:
  - 1.0
  - 1.1
  - tip

install:
  - sudo apt-get install libmagickwand-dev -qq -y
  - export CGO_CFLAGS="-I`pkg-config --cflags MagickWand`"
  - export CGO_LDFLAGS="-I`pkg-config --libs MagickWand`"
  - make reqs
  - make bindata
  - make testenv

script: "make fulltests"

notifications:
  email: false