language: go

go:
  - 1.0
  - 1.1
  - tip

install:
  - sudo apt-get install imagemagick libmagickwand-dev -qq -y
  - make reqs
  - make bindata
  - make testenv

script: "make fulltests"

notifications:
  email: false