#!/bin/sh
# betty-cropper daemon
# chkconfig: 345 20 80
# description: betty-cropper daemon
# processname: betty-cropper

set -e

# Must be a valid filename
NAME=betty-cropper
DESC="Homestyle image cropping"
PIDFILE=/var/run/$NAME.pid

DAEMON="/usr/local/bin/betty-cropper"
DAEMON_OPTS="--config=/etc/betty-cropper/config.json"
USER=www-data


case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
    start-stop-daemon -b -m --start --quiet --chuid $USER --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
    ;;
  stop)
        echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --chuid $USER --oknodo --pidfile $PIDFILE
        echo "."
    ;;
  restart)
        echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --chuid $USER --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon -b -m --start --quiet --chuid $USER --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0